(* ::Package:: *)

(* ::Input:: *)
(*(*begin parameters need to be adjusted. Everything is in SI unit except all energy. Energy is in meV*)*)
(*Efermi=62; (*unit in meV*)*)
(*kCut=5.0;(*value of kz to cut the integrate, order: e8*)*)
(*B=10.0;*)
(*HbarGamma=0.5;(*linewidth term, unit in meV*)*)
(*n=2;(*calculate all possible transition from bands -n to n*)*)
(*xRange=350;(*plot range of x-axis, photon energy with unit in meV*)*)
(**)
(*(*begin of ordinary parameters*)*)
(*hbar=1.05;(*order: e-34*)*)
(*vf=1.0;(*order: e6*)*)
(*eChar=1.6;(*order: e-19*)*)
(*epsilon0=8.85;(*order: e-12*)*)
(*lb=Sqrt[hbar/(eChar*B)*10];(*order: e-8*)*)
(*Ef=Efermi*1.6/100;(*convert meV into Joul, with order:e-20*)*)
(*hbarGamma=HbarGamma*1.6/100;(*convert meV into Joul, with order:e-20*)*)
(**)
(*(*some functions defined*)*)
(*Engy[n_,kz_]:= If[n==0,-hbar*vf*kz,Sign[n]*hbar*vf*Sqrt[2Abs[n]/lb^2+kz^2]];*)
(*nu[n_,kz_]:=Sqrt[(1-hbar*vf*kz/Engy[n,kz])/2];*)
(*mu[n_,kz_]:=Sqrt[(1+hbar*vf*kz/Engy[n,kz])/2];*)
(*c[n_]:=If[n==0,1,1/Sqrt[2]];*)
(*ReConductRHS[n_,m_,kz_,hbarOmega_]:=eChar^2*vf^2*hbar*(c[n]*c[m]*nu[m,kz]*mu[n,kz])^2/(2*Pi^2*lb^2*(Engy[n,kz]-Engy[m,kz]))*hbarGamma/((Engy[n,kz]-Engy[m,kz]-hbarOmega)^2+hbarGamma^2)*(UnitStep[Ef-Engy[m,kz]]-UnitStep[Ef-Engy[n,kz]]);*)
(*ImConductRHS[n_,m_,kz_,hbarOmega_]:=eChar^2*vf^2*hbar*(c[n]*c[m]*nu[m,kz]*mu[n,kz])^2/(2*Pi^2*lb^2*(Engy[n,kz]-Engy[m,kz]))*(hbarOmega-Engy[n,kz]+Engy[m,kz])/((Engy[n,kz]-Engy[m,kz]-hbarOmega)^2+hbarGamma^2)*(UnitStep[Ef-Engy[m,kz]]-UnitStep[Ef-Engy[n,kz]]);*)
(*ReConTotRHS[n_,m_,hbarOmega_]:=NIntegrate[ReConductRHS[n,m,kz,hbarOmega*1.6/100],{kz,-kCut,kCut}];*)
(*ImConTotRHS[n_,m_,hbarOmega_]:=NIntegrate[ImConductRHS[n,m,kz,hbarOmega*1.6/100],{kz,-kCut,kCut}];*)
(**)
(*ReConductLHS[n_,m_,kz_,hbarOmega_]:=eChar^2*vf^2*hbar*(c[n]*c[m]*nu[n,kz]*mu[m,kz])^2/(2*Pi^2*lb^2*(Engy[n,kz]-Engy[m,kz]))*hbarGamma/((Engy[n,kz]-Engy[m,kz]-hbarOmega)^2+hbarGamma^2)*(UnitStep[Ef-Engy[m,kz]]-UnitStep[Ef-Engy[n,kz]]);*)
(*ImConductLHS[n_,m_,kz_,hbarOmega_]:=eChar^2*vf^2*hbar*(c[n]*c[m]*nu[n,kz]*mu[m,kz])^2/(2*Pi^2*lb^2*(Engy[n,kz]-Engy[m,kz]))*(hbarOmega-Engy[n,kz]+Engy[m,kz])/((Engy[n,kz]-Engy[m,kz]-hbarOmega)^2+hbarGamma^2)*(UnitStep[Ef-Engy[m,kz]]-UnitStep[Ef-Engy[n,kz]]);*)
(*ReConTotLHS[n_,m_,hbarOmega_]:=NIntegrate[ReConductLHS[n,m,kz,hbarOmega*1.6/100],{kz,-kCut,kCut}];*)
(*ImConTotLHS[n_,m_,hbarOmega_]:=NIntegrate[ImConductLHS[n,m,kz,hbarOmega*1.6/100],{kz,-kCut,kCut}];*)
(**)
(*ReConAllBandsRHS[hbarOmega_]:=Sum[ReConTotRHS[i,i-1,hbarOmega],{i,1,n}]+Sum[ReConTotRHS[i,-i+1,hbarOmega],{i,2,n}];*)
(*ImConAllBandsRHS[hbarOmega_]:=Sum[ImConTotRHS[i,i-1,hbarOmega],{i,1,n}]+Sum[ImConTotRHS[i,-i+1,hbarOmega],{i,2,n}];*)
(*ReConAllBandsLHS[hbarOmega_]:=Sum[ReConTotLHS[-i+1,-i,hbarOmega],{i,1,n}]+Sum[ReConTotLHS[i-1,-i,hbarOmega],{i,2,n}];*)
(*ImConAllBandsLHS[hbarOmega_]:=Sum[ImConTotLHS[-i+1,-i,hbarOmega],{i,1,n}]+Sum[ImConTotLHS[i-1,-i,hbarOmega],{i,2,n}];*)
(*(*End here. Above is the code to calculate one weyl point with certain fermi energy.*)*)
(**)


(* ::Input:: *)
(**)
(*(*Here begins the Plot function to get the picture of Complex Conductivity. X-axis is Real or Imaginary Conductivity in SI unit, order:e4;Y-axis is photon energy unit:meV. *)
(*Please COPY the plot code you need and PASTE to the end of the above code to run*)*)
(**)
(*(*Draw Complex conductivity of a SINGLE weyl point for either RHS or LHS. Please run the Plot seperatly*)*)
(*(*RHS*)*)
(*Plot[{ReConAllBandsRHS[hbarOmega],ImConAllBandsRHS[hbarOmega]},{hbarOmega,0,xRange},PlotRange->All,PlotLegends->"Expressions"];*)
(*(*LHS*)*)
(*Plot[{ReConAllBandsLHS[hbarOmega],ImConAllBandsLHS[hbarOmega]},{hbarOmega,0,xRange},PlotRange->All,PlotLegends->"Expressions"];*)
(**)
(*(*Draw Complex conductivity of a weyl points PAIR for either RHS or LHS. Ef pushed uniformaly. Please run the Plot seperatly*)*)
(*(*RHS*)*)
(*Plot[{2*ReConAllBandsRHS[hbarOmega],2*ImConAllBandsRHS[hbarOmega]},{hbarOmega,0,xRange},PlotRange->All,PlotLegends->"Expressions"];*)
(*(*LHS*)*)
(*Plot[{2*ReConAllBandsLHS[hbarOmega],2*ImConAllBandsLHS[hbarOmega]},{hbarOmega,0,xRange},PlotRange->All,PlotLegends->"Expressions"];*)
(**)
(*(*Draw Complex conductivity of a weyl points PAIR, with Ef pushed by E||B, means Ef in point and -Ef in another point. RHS and LHS has the same result.*)*)
(*Plot[{(ReConAllBandsRHS[hbarOmega]+ReConAllBandsLHS[hbarOmega]),(ImConAllBandsRHS[hbarOmega]+ImConAllBandsLHS[hbarOmega])},{hbarOmega,0,xRange},PlotRange->All,PlotLegends->"Expressions"];*)
